/**
 * POST /api/customers/create
 * Called by: CustomersClient — "Create Account & Send Setup Email" button
 * Auth: Manager and super_admin only (verified server-side)
 * Creates a Supabase auth user, inserts a profile, generates a password
 * recovery link, and sends an account setup email via Resend.
 *
 * Security notes:
 * - Checks for duplicate email before creating the auth user.
 * - Uses Supabase auth.admin.createUser (service role) — never exposes a real password.
 * - Password setup link is generated by Supabase and expires in 24 hours.
 * - Email is validated as a proper address by the email field type on the client;
 *   we perform a format check here as a belt-and-suspenders guard.
 */

import { createAdminClient } from "@/lib/supabase/server";
import { Resend } from "resend";
import { customerSetupEmail } from "@/lib/emails";

/** Basic email format check — not a substitute for server-side validation but catches obvious garbage. */
const EMAIL_REGEX = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;

/**
 * Creates a new customer account with a Supabase-generated password setup link.
 * @param request - POST request with JSON body: { firstName, lastName, email, phone? }
 */
export async function POST(request: Request) {
  // createAdminClient uses the service role key to bypass RLS for user creation.
  const supabase = await createAdminClient();

  // ── Auth & role check ──────────────────────────────────────────────────────
  const {
    data: { user },
  } = await supabase.auth.getUser();

  if (!user) {
    return Response.json({ success: false, error: "Unauthorized" }, { status: 401 });
  }

  const { data: actor } = await supabase
    .from("profiles")
    .select("role")
    .eq("id", user.id)
    .single();

  if (
    !actor ||
    (actor.role !== "manager" && actor.role !== "super_admin")
  ) {
    return Response.json({ success: false, error: "Forbidden" }, { status: 403 });
  }

  // ── Parse and validate body ────────────────────────────────────────────────
  let body: { firstName?: unknown; lastName?: unknown; email?: unknown; phone?: unknown };
  try {
    body = await request.json();
  } catch {
    return Response.json({ success: false, error: "Invalid request body." }, { status: 400 });
  }

  const { firstName, lastName, email, phone } = body;

  if (
    typeof firstName !== "string" || firstName.trim().length === 0 ||
    typeof lastName !== "string" || lastName.trim().length === 0 ||
    typeof email !== "string" || !EMAIL_REGEX.test(email)
  ) {
    return Response.json(
      { success: false, error: "First name, last name, and a valid email are required." },
      { status: 400 }
    );
  }

  const cleanPhone =
    typeof phone === "string" && phone.trim().length > 0
      ? phone.trim()
      : null;

  // ── 1. Duplicate email check ───────────────────────────────────────────────
  const { data: existing } = await supabase
    .from("profiles")
    .select("id")
    .eq("email", email.toLowerCase())
    .maybeSingle();

  if (existing) {
    return Response.json(
      { success: false, error: "An account with this email already exists." },
      { status: 409 }
    );
  }

  // ── 2. Create Supabase auth user ───────────────────────────────────────────
  // A random UUID is used as a throw-away password — the user will never see it.
  // They set their real password via the recovery link sent in step 5.
  const tempPassword = crypto.randomUUID();
  const { data: authData, error: authError } = await supabase.auth.admin.createUser({
    email: email.toLowerCase(),
    password: tempPassword,
    email_confirm: true,
  });

  if (authError || !authData.user) {
    return Response.json(
      { success: false, error: "Failed to create account. Please try again." },
      { status: 500 }
    );
  }

  // ── 3. Insert profile record ───────────────────────────────────────────────
  const { error: profileError } = await supabase.from("profiles").insert({
    id: authData.user.id,
    first_name: firstName.trim(),
    last_name: lastName.trim(),
    email: email.toLowerCase(),
    phone: cleanPhone,
    role: "customer",
  });

  if (profileError) {
    // Best-effort cleanup — remove the orphaned auth user if profile insert fails.
    await supabase.auth.admin.deleteUser(authData.user.id);
    return Response.json(
      { success: false, error: "Failed to save account details. Please try again." },
      { status: 500 }
    );
  }

  // ── 4. Generate password setup link ───────────────────────────────────────
  // Using the 'recovery' flow so the customer lands on the password-reset screen.
  const { data: linkData } = await supabase.auth.admin.generateLink({
    type: "recovery",
    email: email.toLowerCase(),
  });

  const setupLink = linkData?.properties?.action_link ?? null;

  // ── 5. Send account setup email via Resend ─────────────────────────────────
  // Silently skipped if RESEND_API_KEY is not set (local dev without email).
  if (process.env.RESEND_API_KEY && setupLink) {
    const resend = new Resend(process.env.RESEND_API_KEY);
    const { subject, html } = customerSetupEmail({ firstName: firstName.trim(), setupLink });
    await resend.emails.send({
      from: process.env.RESEND_FROM_EMAIL!,
      to: email.toLowerCase(),
      subject,
      html,
    });
  }

  return Response.json({ success: true });
}
