/**
 * GET /api/enrollware/bookmarklet
 * Called by: The instructor's saved bookmark when tapped on an Enrollware page.
 * Auth: None required for this route — the script itself is public JavaScript.
 *       The API key (__k) is injected by the bookmark wrapper at runtime.
 *
 * Returns the latest bookmarklet JavaScript as plain text/javascript.
 * The script uses two variables injected by the bookmark URL wrapper:
 *   __k  — the instructor's API key (embedded in the saved bookmark JS)
 *   __b  — the SuperheroCPR API base URL (embedded at serve time, below)
 *
 * Serving the script from our API (rather than inlining it in the bookmark URL)
 * means we can update the script logic without requiring instructors to
 * re-save their bookmarks.
 *
 * Example bookmark URL saved by the instructor (generated by /admin/enrollware-tool):
 *   javascript:(function(){var __k='API_KEY_HERE';
 *     fetch('https://superherocpr.com/api/enrollware/bookmarklet')
 *     .then(function(r){return r.text()})
 *     .then(function(c){(new Function('__k',c))(__k)})
 *     .catch(function(){alert('Could not load SuperheroCPR Enrollware tool.')})
 *   })()
 */

import { NextRequest } from "next/server";
import { getBookmarkletSource } from "@/lib/enrollware-bookmarklet";
import { enrollwareCorsHeaders } from "@/lib/enrollware-api-auth";

export async function OPTIONS(request: NextRequest) {
  const origin = request.headers.get("Origin");
  return new Response(null, {
    status: 204,
    headers: enrollwareCorsHeaders(origin),
  });
}

export async function GET(request: NextRequest) {
  const origin = request.headers.get("Origin");
  const cors = enrollwareCorsHeaders(origin);

  // Derive the API base URL from the request host so the script works in
  // both staging and production without hardcoding a URL.
  const host = request.headers.get("host") ?? "";
  const proto = request.headers.get("x-forwarded-proto") ?? "https";
  const apiBase = `${proto}://${host}`;

  const scriptContent = getBookmarkletSource(apiBase);

  return new Response(scriptContent, {
    status: 200,
    headers: {
      ...cors,
      "Content-Type": "text/javascript; charset=utf-8",
      // Allow caching for 5 minutes — short enough to pick up updates quickly
      "Cache-Control": "public, max-age=300",
    },
  });
}
