-- Daily access code regeneration via pg_cron.
--
-- BEFORE RUNNING:
--   Enable the pg_cron extension in the Supabase dashboard under
--   Database → Extensions → pg_cron. The CREATE EXTENSION line below is
--   included for completeness but Supabase may require dashboard activation first.
--
-- SCHEDULE: Runs at 00:00 UTC every day.
-- Affects all active instructors and super_admins.
-- Matches the 6-digit zero-padded format generated by /api/rollcall/refresh-my-code.

-- Enable pg_cron (may need to be enabled via Supabase dashboard Extensions tab first)
create extension if not exists pg_cron;

-- ── Function ─────────────────────────────────────────────────────────────────
-- security definer runs as the defining role (postgres), bypassing RLS.
-- This is safe here because the function only updates access codes on instructor rows.
create or replace function public.regenerate_instructor_access_codes()
returns void
language sql
security definer
set search_path = public
as $$
  update profiles
  set
    daily_access_code       = lpad((floor(random() * 1000000))::int::text, 6, '0'),
    access_code_generated_at = now(),
    updated_at               = now()
  where
    role in ('instructor', 'super_admin')
    and (deactivated is null or deactivated = false);
$$;

-- ── Schedule ─────────────────────────────────────────────────────────────────
-- Unschedule first so re-running this migration is idempotent.
select cron.unschedule('regenerate-instructor-access-codes')
where exists (
  select 1 from cron.job where jobname = 'regenerate-instructor-access-codes'
);

select cron.schedule(
  'regenerate-instructor-access-codes',  -- job name (unique key)
  '0 0 * * *',                           -- midnight UTC daily
  'select public.regenerate_instructor_access_codes()'
);
